### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by buqing2009** [RomanRipp/bebop_api#2]
Hi Roman, i clone the spiderkeys/BebopRebopAPI code and compile successfully, and i follow your file structure, but the reslut of catkin_make your source code is failure, i checked your source file, do you miss uploading the file named IBebopInterface.h , Utility/Exceptions.h and so on?

**Comment by RomanRipp** [comment]
bebop_api is a ros wrapper around RomanRipp/BebopRebopAPI. You will need this in order to compile a ros node. Once I am done with BebopRebopAPI it'll be a library that is used by ros node. But for now you will need to compile BebopRebopAPI.

**Comment by buqing2009** [comment]
ok， i see. Thanks
